name: ClearLagTimer
author: [Crazzoxx, TrootCraft]
website: github.com/Melv1no
version: 1.0
main: fr.melv1no.clearlagtimer.ClearLagTimer
softdepend:
  - ClearLag
commands:
  clearlag:
    description: Donne le temps qu il reste avant le prochain clear lag